### ISSUE TITLE
[feat] write the config_validator.py

### ISSUE THREAD

**Issue by vivekkhimani** [torchfl-org/torchfl#23]
### Acceptance Criteria
- The primary goal of this PR is sanitize/validate CLI args or YAML config to be able to spawn a ```torchfl_job```.
- Remember, if ```--config``` is provided, all of the CLI args are overriden.
- Example YAML schema (this is not yet decided). Also, note that all of these fields are not mandatory and we should be able to use the default values as and when required:

```yaml
experiment_name: foo
experiment_version: 0.1.1
datamodule:
  data_directory: DEFAULT
  dataset_group: cifar
  dataset_name: cifar10
  validation_split: 0.1
  train_bs: 32
  validation_bs: 32
  <refer to cli.py for more>...
model:
  name: resnet18
  num_classes: 10
  num_channels: 3
  activation_fn: relu
  pre_trained: true
  feature_extract: true
  optimizer:
    name: adam
    lr: 0.01
pl_trainer:
  <still WIP>
federated:
  is_federated: true
  num_agents: 10
  global_epochs: 10
  local_epochs: 5
  <refer to cli.py for more>...
```
